notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
# os:
#   - linux
#   - osx
language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_TOOL=autotools
  - BUILD_TOOL=autotools ENABLE_MRUBY=yes
  - BUILD_TOOL=autotools ENABLE_JEMALLOC=yes
  - BUILD_TOOL=autotools ENABLE_MRUBY=yes ENABLE_JEMALLOC=yes
  - BUILD_TOOL=autotools CFLAGS=-funsigned-char CXXFLAGS=-funsigned-char
  - BUILD_TOOL=cmake
  - BUILD_TOOL=cmake ENABLE_MRUBY=yes
matrix:
  allow_failures:
    - env: BUILD_TOOL=cmake ENABLE_MRUBY=yes
before_install:
  - rvm use 2.1
install:
  - tools/travis-install.sh
before_script:
  - tools/travis-before-script.sh
script:
  - tools/travis-script.sh
