notifications:
  webhooks:
    - https://webhook.commit-email.info/

language: cpp

dist: xenial

services:
  - docker

cache:
  - ccache

addons_linux_build: &addons_linux_build
  apt:
    packages:
      - autoconf-archive
      - automake1.11
      - autotools-dev
      - cmake
      - gdb
      - libevent-dev
      - libluajit-5.1-dev
      - libmecab-dev
      - libmsgpack-dev
      - mecab-naist-jdic
      - rapidjson-dev
      - zlib1g-dev

addons_macos_build: &addons_macos_build
  homebrew:
    brewfile: true

addons_linux_docker: &addons_linux_docker
  apt:
    packages:
      - autotools-dev
      - autoconf-archive

matrix:
  include:
    - name: "Autotools"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=autotools
        - CFLAGS=-funsigned-char
        - CXXFLAGS=-funsigned-char
    - name: "Autotools: mruby"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "Autotools: mruby: optimize"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
        - GRN_EXPR_OPTIMIZE=yes
    - name: "Autotools: clang"
      os: linux
      compiler: clang
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "CMake"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
    - name: "CMake: mruby"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "CMake: clang"
      os: linux
      compiler: clang
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "Autotools: macOS"
      os: osx
      compiler: clang
      osx_image: xcode10.2
      addons:
        <<: *addons_macos_build
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "CMake: macOS"
      os: osx
      compiler: clang
      osx_image: xcode10.2
      addons:
        <<: *addons_macos_build
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "Ubuntu 16.04"
      os: linux
      addons:
        <<: *addons_linux_docker
      env:
        - DOCKER=ubuntu-16.04
    - name: "Ubuntu 18.04"
      os: linux
      addons:
        <<: *addons_linux_docker
      env:
        - DOCKER=ubuntu-18.04
    - name: "MinGW32"
      os: linux
      addons:
        <<: *addons_linux_build
      env:
        - TARGET=windows
        - ARCHITECTURES=x86
    - name: "MinGW64"
      os: linux
      addons:
        <<: *addons_linux_build
      env:
        - TARGET=windows
        - ARCHITECTURES=x64

install:
  - travis/install.sh

before_script:
  - travis/before-script.sh

script:
  - travis/script.sh
