notifications:
  webhooks:
    - https://webhook.commit-email.info/

language: cpp

dist: xenial

services:
  - docker

rvm: 2.6

matrix:
  include:
    - name: "Autotools"
      os: linux
      compiler: gcc
      env:
        - BUILD_TOOL=autotools
        - CFLAGS=-funsigned-char
        - CXXFLAGS=-funsigned-char
    - name: "Autotools: mruby"
      os: linux
      compiler: gcc
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "Autotools: mruby: optimize"
      os: linux
      compiler: gcc
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
        - GRN_EXPR_OPTIMIZE=yes
    - name: "Autotools: clang"
      os: linux
      compiler: clang
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "CMake"
      os: linux
      compiler: gcc
      env:
        - BUILD_TOOL=cmake
    - name: "CMake: mruby"
      os: linux
      compiler: gcc
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "CMake: clang"
      os: linux
      compiler: clang
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "Autotools: macOS"
      os: osx
      compiler: clang
      env:
        - BUILD_TOOL=autotools
        - ENABLE_MRUBY=yes
    - name: "CMake: macOS"
      os: osx
      compiler: clang
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "Ubuntu 14.04"
      os: linux
      env:
        - DOCKER=ubuntu-14.04
    - name: "Ubuntu 16.04"
      os: linux
      env:
        - DOCKER=ubuntu-16.04
    - name: "Ubuntu 18.04"
      os: linux
      env:
        - DOCKER=ubuntu-18.04
    - name: "MinGW32"
      os: linux
      env:
        - TARGET=windows
        - ARCHITECTURES=x86
    - name: "MinGW64"
      os: linux
      env:
        - TARGET=windows
        - ARCHITECTURES=x64

before_install:
  - gem update bundler

install:
  - travis/install.sh

before_script:
  - travis/before-script.sh

script:
  - travis/script.sh
