notifications:
  webhooks:
    - https://webhook.commit-email.info/

language: cpp

dist: bionic

cache:
  - ccache

addons_linux_build: &addons_linux_build
  apt:
    packages:
      - apt-transport-https
      - autoconf-archive
      - automake1.11
      - autotools-dev
      - cmake
      - gdb
      - gnupg
      - libevent-dev
      - libluajit-5.1-dev
      - libmecab-dev
      - libmsgpack-dev
      - lsb-release
      - mecab-naist-jdic
      - rapidjson-dev
      - wget
      - zlib1g-dev

matrix:
  include:
    - name: "CMake"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
    - name: "CMake: mruby"
      os: linux
      compiler: gcc
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes
    - name: "CMake: clang"
      os: linux
      compiler: clang
      addons:
        <<: *addons_linux_build
      env:
        - BUILD_TOOL=cmake
        - ENABLE_MRUBY=yes

install:
  - travis/install.sh

before_script:
  - travis/before-script.sh

script:
  - travis/script.sh
