name: macOS
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        label:
          - "Autotools"
          - "CMake"
        include:
          - label: "Autotools"
            use-autotools: true
          - label: "CMake"
            use-cmake: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install packages
        run: |
          brew unlink python@3.8
          rm -f /usr/local/bin/2to3
          brew unlink gcc@9
          brew update || :
          brew bundle
      - name: Generate configure
        if: |
          matrix.use-autotools
        run: |
          ./autogen.sh
      - name: Configure
        if: |
          matrix.use-autotools
        run: |
          mkdir -p ../groonga.build
          cd ../groonga.build
          ../groonga/configure \
            --enable-debug \
            --enable-mruby \
            --prefix=/tmp/local \
            --with-ruby \
            PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
      - name: Run CMake
        if: |
          matrix.use-cmake
        run: |
          export SDKROOT="$(xcrun --show-sdk-path)"
          mkdir -p ../groonga.build
          PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig \
            cmake \
              -B ../groonga.build \
              -S . \
              -DCMAKE_INSTALL_PREFIX=/tmp/local \
              -DGRN_WITH_APACHE_ARROW=yes \
              -DGRN_WITH_DEBUG=yes \
              -DGRN_WITH_MRUBY=yes \
              -DRUBY=$(which ruby)
      - name: Build
        run: |
          make -C ../groonga.build -j$(/usr/sbin/sysctl -n hw.ncpu)
      - name: Install test dependencies
        run: |
          gem install \
            groonga-client \
            json \
            pkg-config \
            red-arrow
      - name: Set environment variables
        run: |
          echo "COLUMNS=79" >> ${GITHUB_ENV}
      - name: "Test: stdio"
        run: |
          cd ../groonga.build
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark
      - name: "Test: HTTP: load: Apache Arrow"
        run: |
          cd ../groonga.build
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark \
              --input-type=apache-arrow \
              --interface=http
      - name: "Test: HTTP: command: POST"
        run: |
          cd ../groonga.build
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark \
              --interface=http \
              --use-http-post
      - name: "Test: HTTP: command: chunked"
        run: |
          cd ../groonga.build
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark \
              --interface=http \
              --use-http-chunked
      - name: "Test: HTTP: reference count"
        run: |
          cd ../groonga.build
          export GRN_ENABLE_REFERENCE_COUNT=yes
          BUILD_DIR=$PWD/test/command \
            bash -x ../groonga/test/command/run-test.sh \
              --n-retries=3 \
              --read-timeout=30 \
              --reporter=mark \
              --interface=http
      - name: Install
        run: |
          make -C ../groonga.build install
